#!/bin/bash

DROP_STATUS="$(dropbox status)"

# Define comparison strings
SYNCED="Up to date"
STOPPED="Dropbox isn't running!"
if [ "$DROP_STATUS" == "$STOPPED" ]; then
        echo "  ERROR! ✗ "    # not in sync
elif [ "$DROP_STATUS" == "$SYNCED" ]; then
        echo "  OK ✔ "      # synced
else
        echo "  SYNCING ⟳ "    # syncing
fi
