# Profile Schema Definition
# This file defines the structure and validation rules for dotfiles profiles

profile_schema:
  type: object
  required:
    - profile
    - components
  additionalProperties: false
  
  properties:
    profile:
      type: object
      required:
        - name
        - description
        - version
      additionalProperties: false
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          description: "Profile display name"
        
        description:
          type: string
          minLength: 10
          maxLength: 256
          description: "Profile description"
        
        version:
          type: string
          pattern: "^\\d+\\.\\d+\\.\\d+$"
          description: "Semantic version (e.g., 1.0.0)"
        
        author:
          type: string
          maxLength: 128
          description: "Profile maintainer"
        
        target_os:
          type: array
          items:
            type: string
            enum: ["linux", "macos", "windows"]
          minItems: 1
          uniqueItems: true
          description: "Supported operating systems"
        
        tags:
          type: array
          items:
            type: string
            maxLength: 32
          maxItems: 10
          uniqueItems: true
          description: "Profile tags for categorization"
    
    requirements:
      type: object
      additionalProperties: false
      properties:
        min_memory_gb:
          type: number
          minimum: 1
          maximum: 1024
          description: "Minimum RAM requirement in GB"
        
        min_disk_gb:
          type: number
          minimum: 1
          maximum: 10240
          description: "Minimum disk space in GB"
        
        network_required:
          type: boolean
          default: true
          description: "Internet connection required"
        
        sudo_required:
          type: boolean
          default: true
          description: "Root privileges required"
        
        gpu_recommended:
          type: boolean
          default: false
          description: "GPU acceleration recommended"
    
    components:
      type: object
      additionalProperties: false
      properties:
        core:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "Core system components"
        
        cloud:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "Cloud provider tools"
        
        devops:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "DevOps and infrastructure tools"
        
        ai_ml:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "AI/ML development stack"
        
        observability:
          type: array
          items:
            type: string  
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "Monitoring and logging tools"
        
        productivity:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "Development productivity tools"
        
        security:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_]*$"
          uniqueItems: true
          description: "Security hardening components"
    
    configuration:
      type: object
      additionalProperties: true
      properties:
        timezone:
          type: string
          default: "UTC"
          description: "System timezone"
        
        locale:
          type: string
          default: "en_US.UTF-8"
          pattern: "^[a-zA-Z]{2}_[A-Z]{2}\\.(UTF-8|utf8)$"
          description: "System locale"
        
        shell:
          type: string
          default: "zsh"
          enum: ["bash", "zsh", "fish"]
          description: "Default shell"
        
        editor:
          type: string
          default: "vim"
          enum: ["vim", "nvim", "nano", "emacs", "code"]
          description: "Default editor"
        
        custom_settings:
          type: object
          additionalProperties: true
          description: "Custom configuration options"
    
    post_install:
      type: object
      additionalProperties: false
      properties:
        scripts:
          type: array
          items:
            type: string
            pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_./]*\\.(sh|py|rb)$"
          uniqueItems: true
          description: "Post-installation scripts"
        
        manual_steps:
          type: array
          items:
            type: string
            minLength: 5
            maxLength: 256
          description: "Manual configuration steps"
        
        validation:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 256
          uniqueItems: true
          description: "Validation commands"